openapi: 3.0.0
info:
  title: API Документация
  version: 1.0.0
  description: Документация сервиса авторизации

servers:
  - url: http://localhost:8000
    description: Локальный сервер

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  /api/registration:
    post:
      summary: Регистрация нового пользователя
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: 12345678
      responses:
        '200':
          description: Пользователь успешно создан
        '400':
          description: Ошибка валидации
        '500':
          description: Ошибка работы сервиса

  /api/login:
    post:
      summary: Авторизация сессии
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: 12345678
      responses:
        '200':
          description: Пользователь успешно авторизован
        '400':
          description: Ошибка валидации или пользователь не существует
        '500':
          description: Ошибка работы сервиса

  /api/refresh:
    post:
      summary: Обновление сессии
      tags: [ Auth ]
      description:
        Обновляет access и refresh токены пользователя. 
        В документации может не работать, так как требует refreshToken из куки.
      responses:
        '200':
          description: Токены успешно обновлены
          content: { }
        '404':
          description: Отсутствует refreshToken
        '500':
          description: Ошибка работы сервиса

  /api/logout:
    post:
      summary: Выход из сессии
      tags: [Auth]
      description:
        Удаляет сессию пользователя и изымает refreshToken.
        В документации может не работать, так как требует refreshToken из куки.
      responses:
        '200':
          description: Успешный выход
          content: {}
        '401':
          description: Пользователь не авторизован
        '500':
          description: Ошибка работы сервиса